---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: satisfactory
spec:
  selector:
    matchLabels:
      app: satisfactory
  serviceName: "satisfactory"
  replicas: 1
  template:
    metadata:
      labels:
        app: satisfactory
    spec:
      containers:
        - name: satisfactory
          image: wolveix/satisfactory-server:latest
          env:
            - name: DEBUG
              value: "false"
            - name: MAXPLAYERS
              value: "8"
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: SKIPUPDATE
              value: "false"
            - name: STEAMBETA
              value: "false"
          ports:
            - name: "api"
              containerPort: 7777
              protocol: TCP
            - name: "game"
              containerPort: 7777
              protocol: UDP
            - name: "messaging"
              containerPort: 8888
              protocol: TCP
          volumeMounts:
            - name: satisfactory-config
              mountPath: /config
            - name: satisfactory-data
              mountPath: /config/gamefiles
          livenessProbe:
            exec:
              command:
              - "/bin/sh"
              - "-c"
              - "/home/steam/healthcheck.sh"
            initialDelaySeconds: 300
            failureThreshold: 4
            successThreshold: 1
            periodSeconds: 30
  volumeClaimTemplates:
    - metadata:
        name: satisfactory-config
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
    - metadata:
        name: satisfactory-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 20Gi
